"""create documents table

Revision ID: a0cf91890ed7
Revises: 8c410dad7ec7
Create Date: 2026-05-11 12:29:28.760121

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a0cf91890ed7'
down_revision: Union[str, Sequence[str], None] = '8c410dad7ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
