"""add extraction fields

Revision ID: b246d93611c5
Revises: ce0d0fe24506
Create Date: 2026-05-08 11:33:12.630747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b246d93611c5'
down_revision: Union[str, Sequence[str], None] = 'ce0d0fe24506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_data', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('processing_time', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'failure_reason')
    op.drop_column('documents', 'processing_time')
    op.drop_column('documents', 'extracted_data')
    # ### end Alembic commands ###
