"""initial migration

Revision ID: fd833d402a60
Revises: a0cf91890ed7
Create Date: 2026-05-11 07:34:12.956603

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fd833d402a60'
down_revision: Union[str, Sequence[str], None] = 'a0cf91890ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
